### ISSUE TITLE
Old Damage Data Values (1.15.2)

### ISSUE THREAD

**Issue by Feathertoes** [Fuzss/swordblockingcombat#14]
this mod is great, only gripe is that it often switches its damage values back to 1.9+ damage values, making swords obsolete essentially, and completely breaking the mod

**Comment by Fuzss** [comment]
Hopefully fixed in db12a25

**Comment by AvrgDerk** [comment]
You can manually change the values to what you want them at within material master settings. Try pasting these into attack damage list, I made changes to all the tool damage values except for hoes.
"minecraft:wooden_axe,-4", "minecraft:golden_axe,-4", "minecraft:stone_axe,-5", "minecraft:iron_axe,-4", "minecraft:diamond_axe,-3", "minecraft:wooden_shovel,-1.5", "minecraft:golden_shovel,-1.5", "minecraft:stone_shovel,-1.5", "minecraft:iron_shovel,-1.5", "minecraft:diamond_shovel,-1.5"
