### ISSUE TITLE
Optifine 1.14 Crash

### ISSUE THREAD

**Issue by nodogsleft** [Fuzss/swordblockingcombat#5]
When clicking on the video settings tab in options with Optifine installed, the game displays "Saving world..." upon a dirt background, which occurs whether or not you're actually in a singleplayer world, followed by a crash. The issue persisted even after deleting my options files in the .minecraft folder. I haven't tested the possibility of crashes for other buttons, but it's a peculiar issue nonetheless.  

Optifine 1.14 F4 & F5
Forge 1.14.4 28.2.0

Crash log: https://pastebin.com/SQ74PHnV

**Comment by Fuzss** [comment]
Disabling the "Disable Attack Indicator" setting will fix this temporarily.

**Comment by Fuzss** [comment]
Fixed in v1.3.1.
