### ISSUE TITLE
[ENHANCEMENT](1.12) Combat test - Knockback

### ISSUE THREAD

**Issue by Foreck1** [Fuzss/swordblockingcombat#6]
I'm aware that this module is not enabled for 1.12 version, but there are some features that are really needed in that version which no other modded has fixed. I'm primarily talking about fixing knockback to work as it should, a scaling attribute instead of a yes or no one.

It would fix huge amounts of problems for modpacks and other mods that play on that game mechanic. There are other mechanics too that would work very well like no damage immunity (since the mod NoDami can be a bit glitchy sometimes), coyote time and swing animation.

Thanks for your time. Hopefully you'll keep improving this awesome mod, I really appreciate the level of customization it offers

**Comment by Fuzss** [comment]
Added linear knockback in 0cbe3c4
The rest requires core modding which the 1.12 doesn't do.
