### ISSUE TITLE
Tetra swords not blocking on 1.15.2

### ISSUE THREAD

**Issue by YTFrost** [Fuzss/swordblockingcombat#7]
**Forge:**
Forge 31.1.37

**Mods included:**
-Just Enough Items v6.0.03
-MaterialMaster v1.1.3
-mgui v2.1.1
-SwordBlockingCombat v1.4
-Tetra v2.3.0

**Description:**
Tetra swords don't work with the blocking feature, even after including them in the list on the config file.
![image](https://user-images.githubusercontent.com/55927438/79236305-13fb6900-7e6d-11ea-8095-7d2a9eb75fde.png)

**Comment by MakcSan** [comment]
same in 1.14.4 
i tried
"Blocking Inclusion List" = ["tetra:sword_modular"]
and
"Blocking Inclusion List" = ["tetra:modular_sword"]
and
"Blocking Inclusion List" = [
"tetra:modular_sword"
]

Everysingle i tried doesn't work, but config is seems to be loading correctly

**Comment by Fuzss** [comment]
Hopefully fixed in db12a25
