### ISSUE TITLE
Useless swords ignoring Exclusion config option [1.15.2]

### ISSUE THREAD

**Issue by mr-poyo** [Fuzss/swordblockingcombat#8]
**Forge:** 31.1.77
**Version:** SwordBlockingCombat-v1.4-1.15.2

I'm trying to have some swords from "Useless Swords" on the exlcusion list as some of them have right-click functions. After various failed attempts, I decided to just wildcard the whole mod as a test and it still doesn't exclude from blocking:

	#Swords to exclude from blocking. Intended for modded swords that already have their own right-click function.
	#Format for every entry is "<namespace>:<path>". Path may use single asterisk as wildcard parameter.
	"Blocking Exclusion List" = ["useless_sword:*"]

**Comment by YTFrost** [comment]
Seems like the same happens with weapons from Silents Gear

**Comment by Fuzss** [comment]
Hopefully fixed in db12a25
