### ISSUE TITLE
Item Specific Attack Cooldown Option

### ISSUE THREAD

**Issue by Camawama** [Fuzss/swordblockingcombat#9]
Could you possibly add a way to enable the attack cooldown only for certain tools? I want to make it so that the Axe still has a small cooldown but the sword doesn't have one at all. Axes are pretty powerful, so being able to swing them fast is a bit too powerful :)

**Comment by Fuzss** [comment]
You can use my other mod Material Master (which is a dependency for this one anyways) to set a custom attack speed for individual items.
